site_name: MLX-Audio

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Tutorials: code-examples.md
  - Web Interface and API Server: web.md

theme: 

  font:
    text: Comfortaa Normal
    code: Comfortaa Light

  name: material
  palette:
    - scheme: default
      toggle: 
      icon: material/weather-night
      name: Light mode
      primary: blue
      accent: white




markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences

plugins:
  - search:
      lang: en